package com.ipaulpro.afilechooser.utils;

import android.net.Uri;
import android.webkit.MimeTypeMap;

import com.ipaulpro.afilechooser.FileChooserActivity;

import java.util.HashMap;
import java.util.Map;

// Class generated by jadx decompiler (1.5.1)
/* loaded from: classes.dex */
public class MimeTypes {
    private final Map<String, String> mMimeTypes = new HashMap();

    public void put(String type, String extension) {
        this.mMimeTypes.put(type, extension.toLowerCase());
    }

    public String getMimeType(String filename) {
        String webkitMimeType;
        String extension = FileUtils.getExtension(filename);
        if (extension.length() <= 0 || (webkitMimeType = MimeTypeMap.getSingleton().getMimeTypeFromExtension(extension.substring(1))) == null) {
            String mimetype = this.mMimeTypes.get(extension.toLowerCase());
            if (mimetype == null) {
                mimetype = FileChooserActivity.MIME_TYPE_ALL;
            }
            return mimetype;
        }
        return webkitMimeType;
    }

    public String getMimeType(Uri uri) {
        return getMimeType(FileUtils.getFile(uri).getName());
    }
}
